name: pomodoro - build & deploy to AWS EC2
env:
  ARTIFACT_NAME: build_artifact
  ARTIFACT_FILE_PATH: build.tar

on:
  push:
    branches: [pomodoro_app]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Flutter
        id: flutter-action
        uses: subosito/flutter-action@main
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"

      - name: Build web application
        run: flutter build web

      - name: Tar build files
        run: tar cvf build.tar build/web

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_FILE_PATH }}
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      KEY_FILE: github_action.pem
      TARGET_DIR: /var/www
      BUILD_DIR: pomodoro
      TMP_DIR: tmp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get public ip4
        id: ip4
        run: |
          ip=$(curl -s https://api.ipify.org)
          echo "ip4=${ip}" >> "$GITHUB_OUTPUT"

      - name: Create SSH key
        env:
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          echo "$SSH_KEY" >> $HOME/${{ env.KEY_FILE }}
          chmod 400 $HOME/${{ env.KEY_FILE }}

      - name: Get build artifact
        uses: actions/download-artifact@v4
        id: get_artifact
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.TMP_DIR }}

      - name: Display downloaded files
        run: |
          echo ${{ steps.get_artifact.outputs.download-path }}

          pwd

          tar tf ${{ steps.get_artifact.outputs.download-path }}/${{ env.ARTIFACT_FILE_PATH }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add Github Actions IP to Security group
        env:
          IP: ${{ steps.ip4.outputs.ip4 }}
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SECURITY_GROUP }} --protocol tcp --port 22 --cidr ${IP}/32

      - name: Upload build files to EC2
        env:
          SSH_USER: ${{ secrets.AWS_EC2_USER }}
          SSH_HOSTNAME: ${{ secrets.AWS_EC2_HOST }}
          SCP_TARGET_PATH: ${{ steps.get_artifact.outputs.download-path }}/${{ env.ARTIFACT_FILE_PATH }}
        run: scp -i $HOME/${{ env.KEY_FILE }} -o StrictHostKeyChecking=no ${{ env.SCP_TARGET_PATH }} ${SSH_USER}@${SSH_HOSTNAME}:${{ env.TARGET_DIR }}

      - name: Connect to EC2 by SSH
        env:
          SSH_USER: ${{ secrets.AWS_EC2_USER }}
          SSH_HOSTNAME: ${{ secrets.AWS_EC2_HOST }}
        run: |
          ssh -i $HOME/${{ env.KEY_FILE }} -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOSTNAME} '
            cd ${{ env.TARGET_DIR }}

            if [ ! -d ${{ env.BUILD_DIR }} ]; then
              mkdir ${{ env.BUILD_DIR }}
            fi

            tar xvf ${{ env.ARTIFACT_FILE_PATH }} -C ${{ env.BUILD_DIR }} --strip-component=1

            ls ${{ env.BUILD_DIR }}

            rm ${{ env.ARTIFACT_FILE_PATH }}
          '

      - name: Remove Github Actions IP From Security Group
        if: always()
        env:
          IP: ${{ steps.ip4.outputs.ip4 }}
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SECURITY_GROUP }} --protocol tcp --port 22 --cidr ${IP}/32
